project: #项目信息
 name: tx-demo-client3
 server:
   transaction: tx-demo-server
 server-url:
   transaction: http://localhost:8937
    
server.port: 8939
 
spring: #应用配置
  application:
    name: ${project.name} 
    
feign:
  hystrix:
    enabled: true
    
master: #主数据库配置
 db:
  type: mysql
  url: jdbc:mysql://192.168.10.73:3306/sgp_tx?useUnicode=true&characterEncoding=UTF-8&generateSimpleParameterMetadata=true&serverTimezone=Asia/Shanghai
  username: root
  password: hbasesoft.com
  
cache: #缓存配置
  model: SIMPLE
  
job:
  register:
    url: localhost:2181
    namespace: ${project.name}
  event:
    enable: false